name: Test, Build & Deploy
on: workflow_dispatch
jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest
        environment: tests
        env:
            APP_KEY: ${{ secrets.APP_KEY }}
        steps:
            - name: Setup Env
              uses: './.github/actions/setup-env'
            - name: Run unit tests
              run: npm run test:unit
    build:
        name: Build
        needs: tests
        runs-on: ubuntu-latest
        environment: build
        env:
            APP_ENV: production
            APP_KEY: ${{ secrets.APP_KEY }}
            DB_TYPE: postgres
            DB_HOST: ${{ secrets.DB_HOST }}
            DB_PORT: ${{ secrets.DB_PORT }}
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASS: ${{ secrets.DB_PASS }}
            DB_NAME: ${{ secrets.DB_NAME }}
        steps:
            - name: Setup Env
              uses: './.github/actions/setup-env'
            - name: Build
              run: npm run build
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: my-metricts-build
                path: |
                  dist
                  package.json
                  .env.example
                retention-days: 7
    deploy:
      name: Deploy
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Download builded artifact
          uses: actions/download-artifact@v4
          with:
            name: my-metricts-build
        - name: Output contents
          run: ls
        - name: Deploy
          run: echo "Deploying..."