name: Run unit tests
on: [push]
jobs:
    run-unit-tests:
        name: Run unit tests
        runs-on: ubuntu-latest
        environment: tests
        env:
            APP_KEY: ${{ secrets.APP_KEY }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Node.js 20
              uses: actions/setup-node@v4
              with:
                node-version: 20
            - name: Cache dependencies
              uses: actions/cache@v4
              id: cache-dependencies
              with:
                path: node_modules
                key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
            - name: Install dependencies
              if: steps.cache-dependencies.outputs.cache-hit != 'true'
              run: npm ci
            - name: Run unit tests
              run: npm run test:unit